site_name: low level
#markdown_extensions: [math]
markdown_extensions:
  - pymdownx.snippets
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- Home: index.md
- Computer:
  - Hardware: hw.md
  - Architectures:
    - General: arch/index.md
    - ARM: arch/arm.md
    - AVR: arch/avr.md
    - MIPS: arch/mips.md
    - X86/AMD64: arch/x86.md
  - OS:
    - 'Home': os/index.md
    - 'Windows': os/windows.md
  - Embedded Systems:
    - General: embedded/index.md
    - Microcontrollers: embedded/micro.md
    - Build&Integration systems: embedded/build.md
    - Boards: embedded/board.md
  - Shells: shell.md
  - Formats: formats.md
  - Filesystem: filesystem.md
  - Applications:
    - General: applications/index.md
    - Vim: applications/vim.md
    - Gdb: applications/gdb.md
    - Git: applications/git.md
    - Qt: applications/qt.md
    - nmap: applications/nmap.md
    - SSH: applications/ssh.md
- Programming:
  - Home: programming/programming.md
  - Algorithms: programming/algorithms.md
  - Design Patterns: programming/design_patterns.md
  - Build systems: programming/build.md
  - Data structures: data_structures/index.md
  - Graphics: data_structures/graphics.md
  - Languages:
    - C++: languages/cpp.md
    - Python: languages/python.md
    - Verilog: languages/verilog.md
  - Ptrace: programming/ptrace.md
  - Randomness: programming/randomness.md
  - Memory: programming/memory.md
  - Computer vision&Machine learning: programming/cv.md
  - Web: programming/web.md
- Security:
  - 'Home': security/index.md
  - 'Browers': security/browser.md
  - 'Crypto': security/crypto.md
  - 'CTF': security/ctf.md
  - 'CVE': security/cve.md
  - 'Hardware': security/hardware.md
  - 'Heap': security/heap.md
  - 'Kernel': security/kernel.md
  - 'Malware&Rootkit': security/malware.md
  - 'Video':    security/video.md
  - 'Reverse shell': security/reverse-shell.md
  - Remote code execution: security/rce.md
  - Shellcode: shellcode.md
  - Counter measure: counter-measure.md
  - Sandbox: security/sandbox.md
  - Fuzzing: fuzzing.md
  - Web:
    - 'Home': security/web/index.md
    - 'XXE': security/web/xxe.md
    - 'XSS': security/web/xss.md
- Reversing:
  - Home: reversing/reversing.md
  - Ghidra: reversing/ghidra.md
  - Radare2: reversing/radare2.md
- Networking:
  - Home: networking.md
  - Iptables: networking/iptables.md
- Physics: physics.md
theme: readthedocs
